# Generated by Django 3.2.10 on 2021-12-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_subject_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='initials',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
