# Generated by Django 3.2.10 on 2021-12-19 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klasat', '0005_remove_class_subject'),
        ('api', '0006_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='class_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='klasat.class'),
        ),
    ]
