# Generated by Django 3.2.10 on 2021-12-19 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_student_class_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='amze_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
