# Generated by Django 3.2.10 on 2021-12-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20211220_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='nid',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
