# Generated by Django 3.2.10 on 2021-12-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_gradevalue_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gradeclass',
            name='grade',
            field=models.IntegerField(),
        ),
    ]
