# Generated by Django 3.2.10 on 2021-12-20 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20211220_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradevalue',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='gradevalue',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='gradevalue',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='gradevalue',
            name='updated_date',
        ),
    ]
