# Generated by Django 3.2.10 on 2021-12-20 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20211220_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='code',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='description',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='title',
        ),
    ]
