# Generated by Django 3.2.10 on 2022-01-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20211220_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradeclass',
            name='description',
        ),
        migrations.RemoveField(
            model_name='gradeclass',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='gradeclass',
            name='grade_type',
        ),
        migrations.RemoveField(
            model_name='gradeclass',
            name='period',
        ),
        migrations.RemoveField(
            model_name='gradeclass',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='gradeclass',
            name='title',
        ),
        migrations.AddField(
            model_name='gradeclass',
            name='first_period_continuous_grade',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gradeclass',
            name='first_period_project_grade',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gradeclass',
            name='first_period_test_grade',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gradeclass',
            name='second_period_continuous_grade',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gradeclass',
            name='second_period_project_grade',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gradeclass',
            name='second_period_test_grade',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gradeclass',
            name='third_period_continuous_grade',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gradeclass',
            name='third_period_project_grade',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gradeclass',
            name='third_period_test_grade',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
