# Generated by Django 3.2.10 on 2022-01-08 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20220108_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gradeclass',
            old_name='third_period_test_grade',
            new_name='test_grade_p3',
        ),
    ]
