# Generated by Django 3.2.10 on 2022-01-08 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klasat', '0005_remove_class_subject'),
        ('api', '0026_rename_gradeclass_gradesclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20)),
                ('continuous_grade_p1', models.FloatField(blank=True)),
                ('project_grade_p1', models.FloatField(blank=True)),
                ('test_grade_p1', models.FloatField(blank=True)),
                ('continuous_grade_p2', models.FloatField(blank=True)),
                ('project_grade_p2', models.FloatField(blank=True)),
                ('test_grade_p2', models.FloatField(blank=True)),
                ('continuous_grade_p3', models.FloatField(blank=True)),
                ('project_grade_p3', models.FloatField(blank=True)),
                ('test_grade_p3', models.FloatField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('classs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klasat.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.studentclass')),
            ],
        ),
    ]
