# Generated by Django 3.2.10 on 2022-01-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20220108_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradeclass',
            name='continuous_grade_p1',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='gradeclass',
            name='continuous_grade_p2',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='gradeclass',
            name='continuous_grade_p3',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='gradeclass',
            name='project_grade_p1',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='gradeclass',
            name='project_grade_p2',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='gradeclass',
            name='project_grade_p3',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='gradeclass',
            name='test_grade_p1',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='gradeclass',
            name='test_grade_p2',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='gradeclass',
            name='test_grade_p3',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
