# Generated by Django 3.2.10 on 2022-01-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20220108_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradeclass',
            name='code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
