# Generated by Django 3.2.10 on 2022-01-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_gradeclass_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeclass',
            name='continuous_grade_p2',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='gradeclass',
            name='continuous_grade_p3',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='gradeclass',
            name='project_grade_p2',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='gradeclass',
            name='project_grade_p3',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='gradeclass',
            name='test_grade_p2',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='gradeclass',
            name='test_grade_p3',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
