# Generated by Django 3.2.10 on 2022-01-08 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20220108_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradeclass',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='gradeclass',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='gradeclass',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='gradeclass',
            name='updated_date',
        ),
    ]
