# Generated by Django 3.2.10 on 2022-01-08 14:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20220108_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeclass',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gradeclass',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gradeclass',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gradeclass',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
