# Generated by Django 3.2.10 on 2021-12-18 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_subject_initials'),
        ('klasat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='subject',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, to='api.subject'),
        ),
    ]
