# Generated by Django 3.2.10 on 2021-12-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klasat', '0002_class_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='class',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
