# Generated by Django 3.2.10 on 2021-12-18 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klasat', '0003_auto_20211218_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='slug',
        ),
    ]
